FROM nvidia/cuda:12.4.1-runtime-ubuntu22.04

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install -y --no-install-recommends \
    python3.11 \
    python3-pip \
    python3-dev \
    python3-venv \
    build-essential \
    libgl1 \
    libglib2.0-0 \
    libsm6 \
    libxext6 \
    libxrender-dev \
    git \
    poppler-utils \
    unzip \
    redis-server \
    nginx \
    && rm -rf /var/lib/apt/lists/*

RUN update-alternatives --install /usr/bin/python python /usr/bin/python3 1

WORKDIR /app

COPY requirements.txt .

RUN pip install --upgrade pip \
    && pip install --no-cache-dir -r requirements.txt

COPY . .

EXPOSE 8000

CMD ["gunicorn", "-w", "1", "-b", "0.0.0.0:8000", "server:app", "--timeout", "600", "--threads", "1"]

# RUN chmod +x ./start.sh

# RUN echo "events { worker_connections 2048; } http { client_max_body_size 1024M; server { listen 8000; location / { add_header Cache-Control no-cache; proxy_pass http://localhost:8001; proxy_intercept_errors on; error_page 502 =200 @502; } location /README.md { root /usr/share/nginx/html; } location @502 { add_header Cache-Control no-cache; root /usr/share/nginx/html; rewrite ^(.*)$ /readme.html break; } }}" > /etc/nginx/nginx.conf

# EXPOSE 8000

# CMD ["sh", "-c", "service nginx start && ./start.sh"]
