version: "3.9"

services:
  server:
    container_name: wood-chipper-ai-server
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - redis
    network_mode: "host"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      # Optionally load .env file automatically instead
      # env_file:
      #   - .env
    command: >
      gunicorn -w 1 -b 0.0.0.0:8000 server:app --timeout 600 --threads 1

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    command: redis-server --save "" --appendonly no
    network_mode: "host"
