FROM pytorch/pytorch:2.4.0-cuda12.4-cudnn9-devel

# Install Python 3.11 if needed
# [Your installation steps here]

# Set environment variables
ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1 \
    PIP_NO_CACHE_DIR=1 \
    LANG=C.UTF-8 \
    LC_ALL=C.UTF-8

# Install necessary packages
RUN apt update && apt install -y \
    redis-tools \
    && rm -rf /var/lib/apt/lists/*

# Set working directory
WORKDIR /wood-chipper-ai

# Copy and install requirements
COPY requirements.txt .
RUN pip install --upgrade pip && pip install -r requirements.txt

# Copy the rest of your application
COPY . .

EXPOSE 8000

CMD ["gunicorn", "--workers=1", "--threads=1", "--bind=0.0.0.0:8000", "src.server:app"]

