version: "3.9"

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - redis
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      # Optionally load .env file automatically instead
      # env_file:
      #   - .env
    command: >
      gunicorn -w 1 -b 0.0.0.0:8000 server:app --timeout 600 --threads 1
    networks:
      - woodchipper-network

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    command: redis-server --save "" --appendonly no
    networks:
      - woodchipper-network

networks:
  woodchipper-network:
    external: true
