services:
  server:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "8000:8000"
    volumes:
      - .:/wood-chipper-ai
    depends_on:
      - redis
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    command: gunicorn -w 1 -b 0.0.0.0:8000 server:app

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    command: redis-server --save "" --appendonly no
